/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.iguimaraes.agendatelefonica.ui;

import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Iago
 */
public class Interface extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
        PopularLista();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jtab = new javax.swing.JTabbedPane();
        tab_addcontato = new javax.swing.JPanel();
        lb_nome = new javax.swing.JLabel();
        lb_dtnasc = new javax.swing.JLabel();
        lb_tel = new javax.swing.JLabel();
        lb_mail = new javax.swing.JLabel();
        txt_nome = new javax.swing.JTextField();
        txt_dtnasc = new javax.swing.JTextField();
        txt_tel = new javax.swing.JTextField();
        txt_mail = new javax.swing.JTextField();
        bt_limpar = new javax.swing.JToggleButton();
        bt_add = new javax.swing.JToggleButton();
        tab_list = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        tab_config = new javax.swing.JPanel();
        lb_servidor = new javax.swing.JLabel();
        lb_senha = new javax.swing.JLabel();
        txt_servidor = new javax.swing.JTextField();
        txt_senha = new javax.swing.JTextField();
        bt_criardb = new javax.swing.JButton();
        lb_usuario = new javax.swing.JLabel();
        txt_usuario = new javax.swing.JTextField();
        lb_porta = new javax.swing.JLabel();
        txt_porta = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Agenda de Contatos");
        setPreferredSize(new java.awt.Dimension(600, 300));
        setResizable(false);

        lb_nome.setText("Nome:");

        lb_dtnasc.setText("Data de Nascimento:");

        lb_tel.setText("Telefone:");

        lb_mail.setText("Email:");

        bt_limpar.setText("Limpar");
        bt_limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_limparActionPerformed(evt);
            }
        });

        bt_add.setText("Adicionar");
        bt_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_addActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tab_addcontatoLayout = new javax.swing.GroupLayout(tab_addcontato);
        tab_addcontato.setLayout(tab_addcontatoLayout);
        tab_addcontatoLayout.setHorizontalGroup(
            tab_addcontatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_addcontatoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tab_addcontatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tab_addcontatoLayout.createSequentialGroup()
                        .addGroup(tab_addcontatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_nome)
                            .addComponent(lb_dtnasc)
                            .addComponent(lb_tel)
                            .addComponent(lb_mail))
                        .addGap(60, 60, 60)
                        .addGroup(tab_addcontatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_nome)
                            .addComponent(txt_dtnasc)
                            .addComponent(txt_tel)
                            .addComponent(txt_mail, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)))
                    .addGroup(tab_addcontatoLayout.createSequentialGroup()
                        .addComponent(bt_limpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bt_add)))
                .addContainerGap())
        );
        tab_addcontatoLayout.setVerticalGroup(
            tab_addcontatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_addcontatoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tab_addcontatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_nome)
                    .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tab_addcontatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_dtnasc)
                    .addComponent(txt_dtnasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tab_addcontatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_tel)
                    .addComponent(txt_tel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tab_addcontatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_mail)
                    .addComponent(txt_mail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                .addGroup(tab_addcontatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_limpar)
                    .addComponent(bt_add))
                .addContainerGap())
        );

        jtab.addTab("Adicionar Contato", tab_addcontato);

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "NOME", "DTNASC", "TELEFONE", "EMAIL"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabela);

        javax.swing.GroupLayout tab_listLayout = new javax.swing.GroupLayout(tab_list);
        tab_list.setLayout(tab_listLayout);
        tab_listLayout.setHorizontalGroup(
            tab_listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE)
        );
        tab_listLayout.setVerticalGroup(
            tab_listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
        );

        jtab.addTab("Lista de Contatos", tab_list);

        lb_servidor.setText("Servidor:");

        lb_senha.setText("Senha:");

        txt_servidor.setText("localhost");

        txt_senha.setText("root");

        bt_criardb.setText("Criar Estrutura");
        bt_criardb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_criardbActionPerformed(evt);
            }
        });

        lb_usuario.setText("Usuario:");

        txt_usuario.setText("root");

        lb_porta.setText("Porta:");

        txt_porta.setText("3306");

        javax.swing.GroupLayout tab_configLayout = new javax.swing.GroupLayout(tab_config);
        tab_config.setLayout(tab_configLayout);
        tab_configLayout.setHorizontalGroup(
            tab_configLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_configLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tab_configLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tab_configLayout.createSequentialGroup()
                        .addComponent(lb_servidor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                        .addComponent(txt_servidor, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tab_configLayout.createSequentialGroup()
                        .addComponent(lb_senha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_senha, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab_configLayout.createSequentialGroup()
                        .addComponent(lb_usuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab_configLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bt_criardb))
                    .addGroup(tab_configLayout.createSequentialGroup()
                        .addComponent(lb_porta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_porta, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        tab_configLayout.setVerticalGroup(
            tab_configLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_configLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tab_configLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_servidor)
                    .addComponent(txt_servidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tab_configLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_porta)
                    .addComponent(txt_porta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tab_configLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_usuario)
                    .addComponent(txt_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tab_configLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_senha)
                    .addComponent(txt_senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                .addComponent(bt_criardb)
                .addContainerGap())
        );

        jtab.addTab("Configuração do Banco de Dados", tab_config);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jtab)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtab)
        );

        jtab.getAccessibleContext().setAccessibleName("jtab");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_addActionPerformed
        // TODO add your handling code here:
        try {
            Connection conn = getConnection();
            String query = "use db_agenda; insert into tb_agenda(nome,dtnasc,telefone,email) values ('" + txt_nome.getText() + "', '" + txt_dtnasc.getText() + "', '" + txt_tel.getText() + "', '" + txt_mail.getText() + "')";
            CallableStatement cs;
            cs = conn.prepareCall(query);
            cs.execute();
            conn.close();
            JOptionPane.showMessageDialog(this, "Adicionado com sucesso!");
            LimparDados();
            PopularLista();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao adicionar contato: " + e.getMessage());
        }
    }//GEN-LAST:event_bt_addActionPerformed

    private void bt_limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_limparActionPerformed
        // TODO add your handling code here:
        LimparDados();
    }//GEN-LAST:event_bt_limparActionPerformed

    private void bt_criardbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_criardbActionPerformed
        // TODO add your handling code here:
        try {
            Connection conn = getConnection();
            String query = "drop database if exists DB_AGENDA; create database DB_AGENDA; use DB_AGENDA; create table TB_AGENDA(ID int auto_increment primary key, NOME varchar(255), DTNASC varchar(20), TELEFONE varchar(20), EMAIL varchar(255));";
            CallableStatement cs;
            cs = conn.prepareCall(query);
            cs.execute();
            conn.close();
            JOptionPane.showMessageDialog(this, "Criado com sucesso!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao criar estrutura: " + e.getMessage());
        }
    }//GEN-LAST:event_bt_criardbActionPerformed

    private void LimparDados() {
        txt_nome.setText("");
        txt_dtnasc.setText("");
        txt_tel.setText("");
        txt_mail.setText("");
    }

    private void PopularLista() {
        try {
            Connection conn = getConnection();
            CallableStatement cs;
            cs = conn.prepareCall("select * from db_agenda.tb_agenda;");
            ResultSet rs = cs.executeQuery();

            while (tabela.getRowCount() > 0) {
                ((DefaultTableModel) tabela.getModel()).removeRow(0);
            }
            
            int columns = rs.getMetaData().getColumnCount();
                       
            while (rs.next()) {
                Object[] row = new Object[columns];
                for (int i = 1; i <= columns; i++) {
                    row[i - 1] = rs.getObject(i);
                }
                ((DefaultTableModel) tabela.getModel()).insertRow(rs.getRow() - 1, row);
            }

            rs.close();
            cs.close();
            conn.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao carregar lista de contatos: " + e.getMessage());
        }
    }

    private Connection getConnection() throws Exception {
        try {
            String driverName = "com.mysql.jdbc.Driver";
            String URL = "jdbc:mysql://" + txt_servidor.getText() + ":" + txt_porta.getText() + "?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&allowMultiQueries=true";
            Class.forName(driverName);
            Connection connection = DriverManager.getConnection(URL, txt_usuario.getText(), txt_senha.getText());
            return connection;
        } catch (Exception e) {
            throw new Exception(e.getMessage());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton bt_add;
    private javax.swing.JButton bt_criardb;
    private javax.swing.JToggleButton bt_limpar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTabbedPane jtab;
    private javax.swing.JLabel lb_dtnasc;
    private javax.swing.JLabel lb_mail;
    private javax.swing.JLabel lb_nome;
    private javax.swing.JLabel lb_porta;
    private javax.swing.JLabel lb_senha;
    private javax.swing.JLabel lb_servidor;
    private javax.swing.JLabel lb_tel;
    private javax.swing.JLabel lb_usuario;
    private javax.swing.JPanel tab_addcontato;
    private javax.swing.JPanel tab_config;
    private javax.swing.JPanel tab_list;
    private javax.swing.JTable tabela;
    private javax.swing.JTextField txt_dtnasc;
    private javax.swing.JTextField txt_mail;
    private javax.swing.JTextField txt_nome;
    private javax.swing.JTextField txt_porta;
    private javax.swing.JTextField txt_senha;
    private javax.swing.JTextField txt_servidor;
    private javax.swing.JTextField txt_tel;
    private javax.swing.JTextField txt_usuario;
    // End of variables declaration//GEN-END:variables
}
